### ISSUE TITLE
Question: What is the relationship between this sdk and using com.vmware.vim.binding.* ?

### ISSUE THREAD

**Issue by SamD** [vmware/vsphere-automation-sdk-java#105]
I'm looking at some legacy code in a project that is interacting using a vlsi-client package that works on these vim bindings. Is anyone familiar with this and could they provide some guidance, is the vsphere-automation-sdk-java is the correct choice moving forward?

**Comment by sumitAgrawal007** [comment]
Vim bindings are in place to cover the parity. It is not officially bundled with the SDK.
You can use vsphere management SDK for vim bindings.
https://code.vmware.com/web/sdk/7.0/vsphere-management

**Comment by SamD** [comment]
Thanks but I was wondering given the various offerings of SDKs, what is the
recommended moving forward?
I would prefer not to have to mix and match multiple sdks to support
features for one product

SD
