### ISSUE TITLE
when I call the cloneVM sample,it report error: operation_not_found

### ISSUE THREAD

**Issue by xianshun163** [vmware/vsphere-automation-sdk-java#108]
- [ ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [ ] This API is compatible with my vCenter version (You can get the info from the Java API Reference Documentation)
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- sdk binding version: 

vsphereautomation-client-sdk-3.3.0.jar
- Java version:

java8
- vSphere version:
6.7 ， is  the clone work well with this version?  
- Operating System/Shell (used to run SDK-based apps):
windows10
## Steps or code snippet to reproduce
When I run the ListVMs ，it work well，  when I  run the cloneVM， It make a err ：
com.vmware.vapi.std.errors.OperationNotFound: OperationNotFound (com.vmware.vapi.std.errors.operation_not_found) => {
## Actual behavior
OperationNotFound

**Comment by pgbidkar** [comment]
Hi @xianshun163 , Clone is not supported in 6.7. API is introduced in vSphere 7.0. Please refer https://code.vmware.com/apis/366/vsphere-automation/VMware-vSphere-Automation-SDK-REST-6.7.0/docs/apidocs/index.html#PKG_com.vmware.vcenter.vm

Thanks

**Comment by xianshun163** [comment]
thank you for your answer
