### ISSUE TITLE
hosting this JAR and other vSphere SDKs on Maven

### ISSUE THREAD

**Issue by ryanpei** [vmware/vsphere-automation-sdk-java#111]
Hi, thanks for creating this automation! I was wondering if there is any plan to host these on Maven or somewhere where Java projects can easily use them.

Do most people otherwise host these themselves on Artifactory?

**Comment by sumitAgrawal007** [comment]
Currently there are no plans to host this on any central repo.
But we are planning to release a new SDK(project is called EVE) where we will have the artifacts hosted in maven repo.

**Comment by ryanpei** [comment]
@sumitAgrawal007 thanks for this update, and do you know when that will be released, approximately?

**Comment by lynch0571** [comment]
I have to say VM SDK is harder to use than AWS.
Hope it gets better.
