### ISSUE TITLE
Fetching detailed information about Hosts within Vcenter

### ISSUE THREAD

**Issue by inshal96** [vmware/vsphere-automation-sdk-java#112]
This might be irrelevant, but no idea where else to post.

I can only fetch identifier, name, power state, and connection state through vsphere 6.5+ rest apis. Is there any way to fetch detailed information about esxi hosts within vcenter 6.0 or above?

**Comment by sumitAgrawal007** [comment]
Hi,
I am not sure if any REST API is available to fetch detailed information about esxi host.
You can go through the available REST APIs here https://developer.vmware.com/docs/vsphere-automation/latest/esx/
There are SOAP APIs available for this.

**Comment by inshal96** [comment]
Hi,
Thank you. That's what I thought, but I wanted confirmation.
I had the task done through vijava. 
Thank you
