### ISSUE TITLE
id = com.vmware.api.vcenter.vm.too_many_matches,     defaultMessage = Too many virtual machines. Add more filter criteria to reduce the number

### ISSUE THREAD

**Issue by aijiaxiang** [vmware/vsphere-automation-sdk-java#121]
I use SDK7.0,Encountered this problem，But I don't know how to set the filter, such as using Cluster

**Comment by sumitAgrawal007** [comment]
I think there are multiple VMs with the same name.
You need to add more filters to the filter spec here
http://build-squid.eng.vmware.com/build/mts/release/bora-17101605/publish/internal/apidocs/restdoc/operations/com/vmware/vcenter/vm.list-operation.html

**Comment by aijiaxiang** [comment]
sorry,I can't open this link


`       VapiAuthHelper vapiHelper = new VapiAuthHelper();
        SslUtil.trustAllHttpsCertificates();


        StubConfiguration stubConfiguration = vapiHelper
                .loginByUsernameAndPassword(vcServer, vcUsername, vcPassword, new HttpConfiguration.Builder().getConfig());
        VM vm = vapiHelper.getStubFactory().createStub(VM.class, stubConfiguration);

        VMTypes.FilterSpec filterSpec = new VMTypes.FilterSpec();
        Set<String> clusters = new HashSet<>();
        clusters.add("HA3-KF3K");        
        filterSpec.setClusters(clusters);

        List<VMTypes.Summary> vmList = vm.list(filterSpec);        

        System.out.println(vmList);`
this is my code,I want to use clusters as a filter condition，The cluster has 36 virtual machines，but I can`t get anyone,the vmList is null.I don't know what's wrong.And this code doesn't report an exception.

**Comment by aijiaxiang** [comment]
> I think there are multiple VMs with the same name.
> You need to add more filters to the filter spec here
> http://build-squid.eng.vmware.com/build/mts/release/bora-17101605/publish/internal/apidocs/restdoc/operations/com/vmware/vcenter/vm.list-operation.html

sorry,I can't open this link.

`VapiAuthHelper vapiHelper = new VapiAuthHelper();
        SslUtil.trustAllHttpsCertificates();
        StubConfiguration stubConfiguration = vapiHelper
                .loginByUsernameAndPassword(vcServer, vcUsername, vcPassword, new HttpConfiguration.Builder().getConfig());
        VM vm = vapiHelper.getStubFactory().createStub(VM.class, stubConfiguration);

        VMTypes.FilterSpec filterSpec = new VMTypes.FilterSpec();
        Set<String> clusters = new HashSet<>();
        clusters.add("HA3-KF3K");
        filterSpec.setClusters(clusters);

        List<VMTypes.Summary> vmList = vm.list(filterSpec);
        System.out.println(vmList);`

This is my code,I want to use clusters as a filter condition，the cluster has 36 virtual machines,but I can't get anyone.the vmList.size()=0.I don't know what's wrong.

**Comment by sumitAgrawal007** [comment]
Sorry, I have updated the link.
Also in the filterspec, the set cluster has to be the Managed object Id of the cluster, not the name of the cluster.

**Comment by aijiaxiang** [comment]
> Sorry, I have updated the link.
> Also in the filterspec, the set cluster has to be the Managed object Id of the cluster, not the name of the cluster.

Thank you very much. I know how to do it
