### ISSUE TITLE
vim25.jar is not compatible with vCenter v7.0U2 (listed as compatible)

### ISSUE THREAD

**Issue by erik-telesoftas** [vmware/vsphere-automation-sdk-java#128]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [ ] This API is compatible with my vCenter version (You can get this info from the API documentation )
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- SDK version: 7.0.U2 (master branch)

- Java version: openjdk version "1.8.0_282"

- vSphere version: 7.0.U2

## Actual behavior

The readme declares compatibility with vCenter v7.0U2, but https://github.com/vmware/vsphere-automation-sdk-java/blob/master/lib/vim25.jar is more than one year old at version 6.7

## Expected behavior

Libraries in this project should be aligned with stated compatible versions of vCenter

**Comment by sumitAgrawal007** [comment]
The bundled vim25.jar is compatible with VC7.0U2 although its an older version. We don't frequently update the vim25.jar with the vsphere-automation-sdk-java. The vim25.jar is only there to cover any missing REST API, if you want the latest vim25.jar, we recommend using the vsphere management sdk.
https://code.vmware.com/web/sdk/7.0/vsphere-management
