### ISSUE TITLE
Is usage of vim25.jar also under MIT license?

### ISSUE THREAD

**Issue by BenDing96** [vmware/vsphere-automation-sdk-java#129]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [x] This API is compatible with my vCenter version (You can get this info from the API documentation )
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues/utf8=%E2%9C%93&q=is%3Aissue)

## Description
- We have the license of vSphere 7.0, 6.7 and 6.5 and want to use vim25.jar for commercial usage. Are vim25.jar and other jar files under lib folder under MIT license as well?

## Environment
- SDK version: 7.0.U2 (master branch)

- Java version: openjdk version "1.8.0_281"

- vSphere version: 7.0.U2

**Comment by sumitAgrawal007** [comment]
All the jars present in lib directory are under MIT license except vim25.jar and ssoclient.jar.
The two jars are present there only to cover the missing REST APIs and the license for them can be found at the download section of https://code.vmware.com/web/sdk/7.0/vsphere-management.
If you want to use only vim25.jar exclusively for development purpose, please use the vsphere management sdk, link shared above.
