### ISSUE TITLE
Is there a way to create, delete and list Linked Clone using vSphere Automation SDK?

### ISSUE THREAD

**Issue by hamSeungWooooo** [vmware/vsphere-automation-sdk-java#154]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [x] This API is compatible with my vCenter version (You can get the info from the Java API Reference Documentation)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- sdk binding version: 7.0.3.0

- Java version: 11.0.12

- vSphere version: 6.7.0.50000

- Operating System/Shell (used to run SDK-based apps): MacOS

##

hello

I have a question.

Is there a way to create, delete and list Linked Clone using vSphere Automation SDK?

I can't find it in the documentation or examples, so I'm asking a question.

Thank you for your reply.

**Comment by jobingeo** [comment]
Linked clone of a VM is based out of snapshot point of a parent VM.
We need to create snapshot [i] of the parent VM, and then pass this snapshot in the cloneSpec[ii] and then call the clone API
These [i] and [ii] capabilities can be achieved with vim25.jar shipped along with this SDK & not with vsphereautomation-client-sdk-xxxx.jar
