### ISSUE TITLE
Attach tag to VM using Java SDK

### ISSUE THREAD

**Issue by Balaji555** [vmware/vsphere-automation-sdk-java#16]
Hi,

Is it possible to attach tag to VM using java ? If possible could you please share the code?  I am searching it from last week and i haven't found anything.
Can you please help me.

**Comment by jobingeo** [comment]
Yes. It's possible to attach a tag to the VM. 
In https://github.com/vmware/vsphere-automation-sdk-java/blob/master/src/main/java/vmware/samples/tagging/workflow/TaggingWorkflow.java , the sample code is to attach a tag to the cluster.  You mayn't find sample code for every inventory entity(eg:VM/Folder/Host etc.)

Please see the code below, which works for the VM. The below code, creates a VM, "Sample-Basic-VM" and attach tags to it.
-------------------------------------------------------------------------------------------------
package vmware.samples.tagging.workflow;

import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.apache.commons.cli.Option;
import com.vmware.cis.tagging.Category;
import com.vmware.cis.tagging.CategoryTypes;
import com.vmware.cis.tagging.Tag;
import com.vmware.cis.tagging.TagAssociation;
import com.vmware.cis.tagging.TagTypes;
import com.vmware.cis.tagging.CategoryModel.Cardinality;
import com.vmware.vapi.std.DynamicID;
import com.vmware.vcenter.VM;
import com.vmware.vcenter.VMTypes;
import com.vmware.vcenter.vm.GuestOS;
import com.vmware.vcenter.vm.hardware.DiskTypes;
import com.vmware.vcenter.vm.hardware.EthernetTypes;
import com.vmware.vcenter.vm.hardware.ScsiAddressSpec;
import com.vmware.vcenter.vm.hardware.EthernetTypes.BackingType;
import com.vmware.vcenter.vm.hardware.boot.DeviceTypes;
import com.vmware.vim25.ManagedObjectReference;

import vmware.samples.common.SamplesAbstractBase;
import vmware.samples.common.vim.helpers.VimUtil;
import vmware.samples.vcenter.helpers.NetworkHelper;
import vmware.samples.vcenter.helpers.PlacementHelper;

public class TaggingWorkflowInVM  extends SamplesAbstractBase{
    private String vmFolderName;
    private String datastoreName;
    private String datacenterName;
    private String clusterName;
    private String standardPortgroupName;
    private static final String BASIC_VM_NAME = "Sample-Basic-VM";
    private GuestOS vmGuestOS = GuestOS.WINDOWS_9_64;
    private VM vmService;
    private String basicVMId;
    
    private Category categoryService;
    private Tag taggingService;
    private TagAssociation tagAssociation;

    private String categoryName = "Asset";
    private String categoryDescription = "All data center assets";
    private String tagName = "Server";
    private String tagDescription = "Cluster running application server";

    private String assetCategoryId;
    private String serverTagId;
    private boolean tagAttached = false;
    private ManagedObjectReference VMMoRef;
    private DynamicID vmDynamicId;

    
    
    
    public static void main(String[] args) throws Exception {
        // TODO Auto-generated method stub
        /*
         * Execute the sample using the command line arguments or parameters
         * from the configuration file. This executes the following steps:
         * 1. Parse the arguments required by the sample
         * 2. Login to the server
         * 3. Setup any resources required by the sample run
         * 4. Run the sample
         * 5. Cleanup any data created by the sample run, if cleanup=true
         * 6. Logout of the server
         */
        new TaggingWorkflowInVM().execute(args);
    }
    /**
     * API to create a category. User who invokes this needs create category
     * privilege.
     *
     * @param name
     * @param description
     * @param cardinality
     * @return
     */
    private String createTagCategory(String name, String description,
                                     Cardinality cardinality) {
        CategoryTypes.CreateSpec createSpec = new CategoryTypes.CreateSpec();
        createSpec.setName(name);
        createSpec.setDescription(description);
        createSpec.setCardinality(cardinality);

        Set<String> associableTypes = new HashSet<String>(); // empty hash set
        createSpec.setAssociableTypes(associableTypes);
        return this.categoryService.create(createSpec);
    }

    /**
     * Deletes an existing tag category; User who invokes this API needs delete
     * privilege on the tag category.
     *
     * @param categoryId
     */
    private void deleteTagCategory(String categoryId) {
        this.categoryService.delete(categoryId);
    }

    /**
     * Creates a tag
     *
     * @param name Display name of the tag.
     * @param description Tag description.
     * @param categoryId ID of the parent category in which this tag will be
     *        created.
     * @return Id of the created tag
     */
    private String createTag(String name, String description,
                             String categoryId) {
        TagTypes.CreateSpec spec = new TagTypes.CreateSpec();
        spec.setName(name);
        spec.setDescription(description);
        spec.setCategoryId(categoryId);

        return this.taggingService.create(spec);
    }

    /**
     * Update the description of an existing tag. User who invokes this API
     * needs edit privilege on the tag.
     *
     * @param tagId the ID of the input tag
     * @param description
     */
    private void updateTag(String tagId, String description) {
        TagTypes.UpdateSpec updateSpec = new TagTypes.UpdateSpec();
        updateSpec.setDescription(description);
        this.taggingService.update(tagId, updateSpec);
    }

    /**
     * Delete an existing tag. User who invokes this API needs delete privilege
     * on the tag.
     *
     * @param tagId the ID of the input tag
     */
    private void deleteTag(String tagId) {
        this.taggingService.delete(tagId);
    }

    


    @Override
    protected void parseArgs(String[] args) {
        Option datacenterOption = Option.builder()
                .longOpt("datacenter")
                .desc("The name of the datacenter on which to create the vm.")
                .argName("DATACENTER")
                .required(true)
                .hasArg()
                .build();
        Option vmFolderOption = Option.builder()
                .longOpt("vmfolder")
                .desc("The name of the vm folder on which to create the vm.")
                .argName("VM FOLDER")
                .required(true)
                .hasArg()
                .build();
        Option datastoreOption = Option.builder()
                .longOpt("datastore")
                .desc("The name of the datastore on which to create the vm")
                .required(true)
                .argName("DATASTORE")
                .hasArg()
                .build();
        Option clusterOption = Option.builder()
                .longOpt("cluster")
                .desc("The name of the cluster on which to create the vm.")
                .argName("CLUSTER")
                .required(true)
                .hasArg()
                .build();
        Option stdPortgroupOption = Option.builder()
                .longOpt("standardportgroup")
                .desc("The name of the standard portgroup")
                .argName("STANDARD PORTGROUP")
                .required(true)
                .hasArg()
                .build();

        List<Option> optionList = Arrays.asList(vmFolderOption,
                datastoreOption,
                datacenterOption,
                clusterOption,
                stdPortgroupOption);

        super.parseArgs(optionList, args);
        this.vmFolderName = (String) parsedOptions.get("vmfolder");
        this.datastoreName = (String) parsedOptions.get("datastore");
        this.datacenterName = (String) parsedOptions.get("datacenter");
        this.clusterName = (String) parsedOptions.get("cluster");
        this.standardPortgroupName = (String) parsedOptions.get(
            "standardportgroup");
    
    }

    @Override
    protected void setup() throws Exception {
        this.vmService = vapiAuthHelper.getStubFactory().createStub(VM.class,
                sessionStubConfig);
        this.categoryService =
                this.vapiAuthHelper.getStubFactory().createStub(Category.class,
                                                           sessionStubConfig);
        this.taggingService =
                this.vapiAuthHelper.getStubFactory().createStub(Tag.class,
                                                           sessionStubConfig);
        this.tagAssociation =
                this.vapiAuthHelper.getStubFactory()
                    .createStub(TagAssociation.class,
                                sessionStubConfig);
    }

    @Override
    protected void run() throws Exception {
        // Get a placement spec
        VMTypes.PlacementSpec vmPlacementSpec = PlacementHelper
            .getPlacementSpecForCluster(this.vapiAuthHelper.getStubFactory(),
                this.sessionStubConfig,
                this.datacenterName,
                this.clusterName,
                this.vmFolderName,
                this.datastoreName);

        // Get a standard network backing
        String standardNetworkBacking = NetworkHelper.getStandardNetworkBacking(
            this.vapiAuthHelper.getStubFactory(),
            this.sessionStubConfig,
            this.datacenterName,
            this.standardPortgroupName);

        // Create the basic VM
        createBasicVM(vmPlacementSpec, standardNetworkBacking);

        // create a new tag category "Asset"
        this.assetCategoryId = createTagCategory(this.categoryName,
                                                 this.categoryDescription,
                                                 Cardinality.MULTIPLE);
        System.out.println("Tag category created; Id: " + this.assetCategoryId);

        // create a new Tag "Server"
        this.serverTagId = createTag(this.tagName, this.tagDescription,
                                     this.assetCategoryId);
        System.out.println("Tag created; Id: " + this.serverTagId);

        // update the asset tag
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.SSS");
        Date dt = new Date();
        String date = sdf.format(dt); // formats to 09/23/2009 13:53:28.238
        updateTag(this.serverTagId, "Server Tag updated at " + date);
        System.out.println("Tag updated; Id: " + this.serverTagId);
        
        // retrieve the VMs MoRef
        this.VMMoRef =
                VimUtil.getVM(this.vimAuthHelper.getVimPort(),
                                   this.vimAuthHelper.getServiceContent(),
                                   BASIC_VM_NAME);
        assert this.VMMoRef != null;
        System.out.println("VM MoRef: " + this.VMMoRef.getValue());
        
     // convert the MoRef to vAPI DyanmicID
        this.vmDynamicId =
                new DynamicID(this.VMMoRef.getType(),
                              this.VMMoRef.getValue());

        // list all the tags that can be attached to the VM
        List<String> attachableTags =
                this.tagAssociation.listAttachableTags(this.vmDynamicId);
        System.out.println("Attachable Tags:\n" + attachableTags
                           + "\nEnd of Attachable tags");
        assert attachableTags.contains(this.serverTagId);
     // tag the VM
        this.tagAssociation.attach(this.serverTagId, this.vmDynamicId);
        assert this.tagAssociation.listAttachedTags(this.vmDynamicId)
                             .contains(this.serverTagId);
        this.tagAttached = true;
        System.out.println("VM: " + this.vmDynamicId + " tagged");
    }

    /*
     * Creates a basic VM on a cluster with the following configuration:
     * - Create 2 disks and specify one of them on scsi0:0 since
     * it's the boot disk.
     * - Specify 1 ethernet adapter using a Standard Portgroup backing.
     * - Setup for PXE install by selecting network as first boot device.
     * - Use guest and system provided defaults for most configuration settings.
     */
    private void createBasicVM(
        VMTypes.PlacementSpec vmPlacementSpec, String standardNetworkBacking) {
        // Create the scsi disk as a boot disk
        DiskTypes.CreateSpec bootDiskCreateSpec =
                new DiskTypes.CreateSpec.Builder().setType(
                    DiskTypes.HostBusAdapterType.SCSI)
                    .setScsi(new ScsiAddressSpec.Builder(0l).setUnit(0l)
                        .build())
                    .setNewVmdk(new DiskTypes.VmdkCreateSpec())
                    .build();

        // Create a data disk
        DiskTypes.CreateSpec dataDiskCreateSpec =
                new DiskTypes.CreateSpec.Builder().setNewVmdk(
                    new DiskTypes.VmdkCreateSpec()).build();
        List<DiskTypes.CreateSpec> disks = Arrays.asList(bootDiskCreateSpec,
            dataDiskCreateSpec);

        // Create a nic with standard network backing
        EthernetTypes.BackingSpec nicBackingSpec =
                new EthernetTypes.BackingSpec.Builder(
                    BackingType.STANDARD_PORTGROUP).setNetwork(
                        standardNetworkBacking).build();
        EthernetTypes.CreateSpec nicCreateSpec =
                new EthernetTypes.CreateSpec.Builder().setStartConnected(true)
                    .setBacking(nicBackingSpec)
                    .build();
        List<EthernetTypes.CreateSpec> nics = Collections.singletonList(
            nicCreateSpec);

        // Specify the boot order
        List<DeviceTypes.EntryCreateSpec> bootDevices = Arrays.asList(
            new DeviceTypes.EntryCreateSpec.Builder(DeviceTypes.Type.ETHERNET)
                .build(),
            new DeviceTypes.EntryCreateSpec.Builder(DeviceTypes.Type.DISK)
                .build());

        VMTypes.CreateSpec vmCreateSpec = new VMTypes.CreateSpec.Builder(
            this.vmGuestOS).setName(BASIC_VM_NAME)
                .setBootDevices(bootDevices)
                .setPlacement(vmPlacementSpec)
                .setNics(nics)
                .setDisks(disks)
                .build();
        System.out.println("\n\n#### Example: Creating Basic VM with spec:\n"
                           + vmCreateSpec);
        this.basicVMId = vmService.create(vmCreateSpec);
        VMTypes.Info vmInfo = vmService.get(this.basicVMId);
        
        System.out.println("\nBasic VM Info:\n" + vmInfo);
    }

    @Override
    protected void cleanup() throws Exception {
        if (this.tagAttached) {
            this.tagAssociation.detach(this.serverTagId, this.vmDynamicId);
            System.out.println("Cluster: " + this.vmDynamicId
                                       + " untagged");
        }

        if (this.serverTagId != null) {
            deleteTag(this.serverTagId);
            System.out.println("Tag deleted; Id: " + this.serverTagId);
        }

        if (this.assetCategoryId != null) {
            deleteTagCategory(this.assetCategoryId);
            System.out.println("Tag category deleted; Id: "
                               + this.assetCategoryId);
        }
        if (this.basicVMId != null) {
            System.out.println("\n\n#### Deleting the Basic VM");
            this.vmService.delete(this.basicVMId);
        }
    }
}

--------------------------------------------------
