### ISSUE TITLE
vmware vsphere vapp

### ISSUE THREAD

**Issue by VGrytsenko2022** [vmware/vsphere-automation-sdk-java#162]
Hello
Is it possible to interact with vApp?
I see only ResourcePools in the documentation.

**Comment by jobingeo** [comment]
Can you please use vim25.jar to interact with vApp.?
Ref: https://developer.vmware.com/apis/1192/vsphere  (createvApp, Import vApp etc..)

**Comment by VGrytsenko2022** [comment]
OK. Thank you.
