### ISSUE TITLE
Get all datastores from the StoragePod (Datastore clusters)

### ISSUE THREAD

**Issue by DashThink** [vmware/vsphere-automation-sdk-java#17]
Hi,

Is it possible to get all the Datastores from the Datastore Cluster(StoragePod) using java. Can you please share the code to retrive the datastores.

Thanks.

**Comment by vinpai** [comment]
Hi DashThink,
You can take a look at an example for getting datastores here - https://github.com/vmware/vsphere-automation-sdk-java/blob/master/src/main/java/vmware/samples/vcenter/helpers/DatastoreHelper.java

We currently support only a few operations on datastores (get, list). For other operations, you will need to use the management sdk. You can take a look at the API docs here - https://code.vmware.com/doc/preview?id=4892
