### ISSUE TITLE
API to import OVF via vCenter to ESXi host

### ISSUE THREAD

**Issue by Tilden18** [vmware/vsphere-automation-sdk-java#173]
Hi All,
We have a problem related to OVF imports in the ESXi host.

We are using the VI Java Client API for our automation.

Our automation works as follows:

Authentication using the https:///sdk
And we upload the OVF templates to ESXi Host
And VM is created
Reference code: https://developer.vmware.com/samples/7622/deploy-ovf?h=ovf#code

Here we have a dependency on ESXi Host connectivity/reachability, or else the OVF import will fail.

We want to break this dependency, maybe by using some vcenter API which will help us to upload the OVF to the ESXi Host via the vcenter, (Similar to Uploading an OVF in vCenter portal).

We are not able to find the right API. Our understanding is, vsphere automation API has features to upload the OVF to the content library and deploy/create an OVF from the content library.

Currently, we don't want to use the content library, so do we have any other API which will help us to achieve our goals?

Describe the solution:
API which will help us to upload the OVF image to the EXSI host via vCenter. So we eliminate the connectivity dependency towards ESXi Host.

**Comment by shwetapurohit** [comment]
@Tilden18 ,
For this, SOAP api can be used.
Here is the API `importVapp`  in https://developer.vmware.com/apis/1355/vsphere
The above reference code also use the same api.
Automation JAVA SDK does not support this.
