### ISSUE TITLE
Update Custom Attributes using java

### ISSUE THREAD

**Issue by DashThink** [vmware/vsphere-automation-sdk-java#18]
Hi,

I want to update the value of existing attribute using java. Does anyone have the code?

Thanks

**Comment by kunal-pmj** [comment]
Can you please elaborate?  What attributes are referring to?
 Thanks

**Comment by Balaji555** [comment]
Thanks for reply. BTW i got the solution. I wanted to update the value to custom attribute of the VM.
It can be achive using vmInstance.setCustomValue("CustAtribute", "TestValue");

**Comment by vinpai** [comment]
Closing this, since you found the solution.
