### ISSUE TITLE
Static IP address assignment

### ISSUE THREAD

**Issue by DashThink** [vmware/vsphere-automation-sdk-java#19]
Is it possible to assign static IP address using Java? Please share the code if it is possible.

**Comment by alanrenouf** [comment]
A Static IP address for what? 

- a VM?, if so which OS
- a ESX Host?

**Comment by Balaji555** [comment]
Yes for the VM with Windows OS...
6.5 version...

**Comment by alanrenouf** [comment]
Not Via this SDK or the REST API at the moment but check out the vSphere Management SDK and the Guest Operations API which allows you to run a 
 command inside the Guest OS and set the IP via that  https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.vm.guest.GuestOperationsManager.html

**Comment by Balaji555** [comment]
Not understood how can I set static IP... found something on above link about the DHCP configuration. But not sure hot to assign to VM. Do have any idea?
https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.net.DhcpConfigInfo.DhcpOptions.html

**Comment by tianhao64** [comment]
You should be able to assign IP by setting ipConfig: https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vim.vm.GuestInfo.NicInfo.html#field_detail

**Comment by Balaji555** [comment]
while cloning the vm i am getting InvalidRequest error..
my code:

CustomizationSpec customSpec = new CustomizationSpec();
			
			 CustomizationGlobalIPSettings gIp = new CustomizationGlobalIPSettings();
		        customSpec.setGlobalIPSettings(gIp);

		        CustomizationFixedIp fixedIp = new CustomizationFixedIp();
		        fixedIp.setIpAddress(ipAddress);

		        CustomizationIPSettings adapter = new CustomizationIPSettings();
		        adapter.setIp(fixedIp);
		        adapter.setDnsServerList(new String[] {dns});
		        adapter.setGateway(new String[] {gateway});
		        //adapter.setSubnetMask(subnet);

		        CustomizationAdapterMapping adapterMap = new CustomizationAdapterMapping();
		        adapterMap.setAdapter(adapter);

		        CustomizationAdapterMapping[] nicSettingMap = new CustomizationAdapterMapping[]{adapterMap};
		        customSpec.setNicSettingMap(nicSettingMap);
		        cloneSpec.setCustomization(customSpec);

**Comment by vinpai** [comment]
Hi Balaji555,
You may post your query at VMware code forums here - https://code.vmware.com/forums/2416/vsphere-management-sdk .

**Comment by bokers** [comment]
I need  to assign  static ipAddres for VM too

**Comment by bokers** [comment]
I have a solution:  keep a  VirtualMachine pool （it looks like  ThreadPool) which managed by background task ，so,   i need to  setting a static IP address of VirtualMachine too


Finally, I got a function to resolve this:  It`s  __Vmware PowerCLI__

> look at https://developer.vmware.com/docs/powercli/latest/vmware.vimautomation.core/commands/invoke-vmscript/

![image](https://github.com/vmware/vsphere-automation-sdk-java/assets/31065222/233f072e-a67c-414f-8971-c67ac93b2f50)


AnyOther for start:

* Step 1:  your Local Machine of Linux  OR  Windows,  need install PowerShell 

* Step 2:  look at this guide:   __https://developer.vmware.com/powercli/installation-guide__


there so many problem of  
- Http RESTFul API
- Web Service SDK  

such as:

- Missing  Snapshot Manage(create、revert、remove)
- can`t send command to VirtualMachine (i found it from vmware support community)
- I try my best to call API "/rest/cis/tasks?filter_spec" (SDK: com.vmware.cis.Tasks), but it looks like can`t work( from vmware support community: some people think that maybe a problem of the interface )

maybe the Web Service SDK REST API work well, but it looks like just support with the Newest product Version
