### ISSUE TITLE
Class cast exception 

### ISSUE THREAD

**Issue by DashThink** [vmware/vsphere-automation-sdk-java#20]
I am updating existing network from the template while cloning (Applying Storage recommandation) .
below is my code......

private VirtualDeviceConfigSpec setVirtualNetwork(VirtualDevice[] vds, String network) {
		VirtualDeviceConfigSpec nicSpec = new VirtualDeviceConfigSpec();
		nicSpec.setOperation(VirtualDeviceConfigSpecOperation.edit);
		for (int i = 0; i < vds.length; i++) {
			if ((vds[i] instanceof VirtualEthernetCard)
					&& (vds[i].getDeviceInfo().getLabel().equalsIgnoreCase("Network Adapter 1"))) {
				VirtualEthernetCard nic = (VirtualEthernetCard) vds[i];
				VirtualDeviceBackingInfo properties = nic.getBacking();
				VirtualEthernetCardNetworkBackingInfo nicBaking = (VirtualEthernetCardNetworkBackingInfo) properties;
				nicBaking.setDeviceName(network);
				nic.setBacking(nicBaking);
				nicSpec.setDevice(nic);
			}
		}
		return nicSpec;

	}
This is my error: any idea why this exception occured? 

java.lang.ClassCastException: com.vmware.vim25.VirtualEthernetCardDistributedVirtualPortBackingInfo cannot be cast to com.vmware.vim25.VirtualEthernetCardNetworkBackingInfo

**Comment by vinpai** [comment]
DashThink,
I am closing this issue, since it looks like an issue in your code. Its hard to troubleshoot what exactly might be wrong from above. If this is still causing an issue, you may try getting help in the community forums here - https://code.vmware.com/forums/2416/vsphere-management-sdk
