### ISSUE TITLE
Deploy or Create a VM from an existing VM template

### ISSUE THREAD

**Issue by ib321** [vmware/vsphere-automation-sdk-java#219]
### Discussed in https://github.com/vmware/vsphere-automation-sdk-java/discussions/218

<div type='discussions-op-text'>

<sup>Originally posted by **ib321** May 25, 2024</sup>
I am trying to **Create a virtual machine from an existing virtual machine template.**
So I was exploring this SDK and I don't seem to find any sample that to do this exactly basic operation.

My Analysis:(pls correct me if I'm wrong)
1. I found CloneVM which clones the VM tried to clone VM temple by passing id of VM template in place of VM. It says VM not found. Meaning it treats VM template and VM differently.
2. Tried DeployVMTemplate class sample. But it seems to be deploying a VM from a library item containing a VM template. And I don't want to create a library Item. Should I?
3. And I tried doing this simple task in GUI vCenter Client manually And I can. refer below:
URL: https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-8F7F6533-C7DB-4800-A8D2-DF7016016A80.html

Please help what are the options for me:
My Analysis:
1. I may use CloneVM class which is working fine. (but it only seems to clone from VM not from VM template.)
but each cloned VM share same DNS? What is solution for this problem? will there be any issue when I try to access those all VM on same network?
2. If I go with wrapping my VM template into content library. Then deploying VM from that content library VM template  using DeployVMTemplate class. MY ADMIN IS NOT HAPPY GIVING ME THE ADMIN ACCESS. As his words are if you are able to deploy VM from VM template on GUI you are fine on access side that's all you can get.

I tried other thing and at last hope
Looking forward for some direction from this community.
Thanks a lot
</div>

**Comment by kunalpmj** [comment]
There is no REST API to deploy a VM from VM template. You can use the vSphere Management SDK to accomplish this task.
The SDK can be downloaded from: https://developer.broadcom.com/sdks/vsphere-management-sdk/latest. 
You can download and unzip the SDK .
The location of the sample is vsphere-ws/java/JAXWS/samples/com/vmware/vm/VMClone.java.

You probably need not switch between different SDKs. The Automation SDK provides the vsphere-ws client binding : https://github.com/vmware/vsphere-automation-sdk-java/blob/e30991881c7e5a68af31e4e774e1a1236d8f2867/pom.xml#L420

You can refer to existing samples to see how to work with different APIs flavours : https://github.com/vmware/vsphere-automation-sdk-java/blob/e30991881c7e5a68af31e4e774e1a1236d8f2867/src/main/java/vmware/samples/common/vim/helpers/VmVappPowerOps.java#L17
