### ISSUE TITLE
Cannot complete vcenter login using SAML token

### ISSUE THREAD

**Issue by indukr** [vmware/vsphere-automation-sdk-java#23]
Hi,

We are using SAML token for vcenter authentication. When we try to login using the Bearer Token, login is failing saying "Cannot complete login due to an incorrect user name or password". 

We are using com.vmaware.VimAuthenticationHelper.loginByToken(vcenter,token) to login into the vcenter. 

**More Details:**
**Token Type**: Bearer Token
**SAML Token generation code snippet** :
SamlToken token =
        SsoHelper.getSamlBearerToken(
            "https://{hostIP}/sts/STSService", "administrator@vsphere.local", "<PASSWORD>")
Vcenter version: 6.5.0.10000 Build 5973321

**Context**: trying to test rest end points using postman/curl and we are getting above exception during vcenter login.

Please find the screenshot of the error we are facing as below:

![image](https://user-images.githubusercontent.com/26592033/34200641-cff9ba06-e597-11e7-983b-db3712f055ea.png)

Please let me know if you need any other details.

Thanks
Rajendra

**Comment by kunal-pmj** [comment]
Kindly try with JDK 1.2.1 or lower. This issue is cased by a JDK bug
https://bugs.openjdk.java.net/browse/JDK-8186441.
You may try  JDK 8u152 b34 or higher where JDK issue has been fixed.
