### ISSUE TITLE
can't find basic operations 

### ISSUE THREAD

**Issue by rdxnaor** [vmware/vsphere-automation-sdk-java#24]
Hi,
Some basic operations are missing. 
1. creating a clone from a VM? thought it will be in VM class but its not there.
2. taking a snapshot on a VM? thought it will be in VM class but its not there.
3. I saw that creating a VM requires a spec. can I create a spec from existing VM?  thought it will be in VM class but its not there.

**Comment by vinpai** [comment]
The vSphere Automation SDK does not support clone and snapshot operations at this time. But we are working hard to get those into the coming releases. Until then, you can use the vSphere Management SDK for these operations.

**Comment by rdxnaor** [comment]
Do you have a due date on that?

**Comment by jobingeo** [comment]
Clone, Relocate and many more operations are now available in latest 7.0 release
