### ISSUE TITLE
This API is not open to Java

### ISSUE THREAD

**Issue by z839978721** [vmware/vsphere-automation-sdk-java#27]
In addition to the main method, there are no other methods that can be called, such as the method with which the parameters are returned.

**Comment by kunal-pmj** [comment]
Can you please elaborate on the problem? 
Are you looking for public methods in the example code to which returns the required parameter?

**Comment by z839978721** [comment]
Please see,Data is not obtained because the method does not return

protected void run() throws Exception {
        Builder bldr = new Builder();
        if(null != this.datacenterName && !this.datacenterName.isEmpty()){
            bldr.setDatacenters(Collections.singleton(DatacenterHelper.
                  getDatacenter(this.vapiAuthHelper.getStubFactory(),
                          this.sessionStubConfig, this.datacenterName)));
        }
        if(null != this.clusterName && !this.clusterName.isEmpty()) {
            bldr.setClusters(Collections.singleton(ClusterHelper.getCluster(
                  this.vapiAuthHelper.getStubFactory(), sessionStubConfig,
                  this.clusterName)));
        }      
        if(null != this.vmFolderName && !this.vmFolderName.isEmpty())
        {
            bldr.setFolders(Collections.singleton(FolderHelper.getFolder(
                  this.vapiAuthHelper.getStubFactory(), sessionStubConfig,
                  this.vmFolderName)));
        }
        List<Summary> vmList = this.vmService.list(bldr.build());
        System.out.println("----------------------------------------");
        System.out.println("List of VMs");
        for (Summary vmSummary : vmList) {
            System.out.println(vmSummary);
        }
        System.out.println("----------------------------------------");
    }

**Comment by vinpai** [comment]
Yes, these samples are not mean't to be used as helper methods and designed to be run independently through the main() method. So, you can't directly call the run() method and expect the same output as executed via main().
