### ISSUE TITLE
Maven repository for vsphere-automation-sdk-java artifacts

### ISSUE THREAD

**Issue by m2spring** [vmware/vsphere-automation-sdk-java#29]
Hi,
is there a Maven repository which carries the [vsphere-automation-sdk-java artifacts](https://github.com/vmware/vsphere-automation-sdk-java/tree/master/lib)?
Having to get binaries from a Git repository is a bit odd, in particular when working with Maven.
Thanks!
-Max

**Comment by lynch0571** [comment]
It has been two years.
Has it been uploaded to the Maven repository?

**Comment by antekone** [comment]
Probably not

**Comment by igolikov** [comment]
> Agreed. We are working to get these artifacts to maven repo, but unfortunately right now this is the only way, until we resolve those issues.

that is just 15 minutes of work
