### ISSUE TITLE
vapi-runtime

### ISSUE THREAD

**Issue by datvmc** [vmware/vsphere-automation-sdk-java#38]
- [ yes] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [ yes] This API is compatible with my vCenter version (You can get this info from the API documentation )
- [ yes] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Description
While trying to get the list of orgs from the ApiClient, I hit this error:
Caused by: java.lang.NoSuchMethodError: com.vmware.vapi.internal.protocol.client.rpc.RestTransport.execute(Lcom/vmware/vapi/internal/protocol/client/rpc/HttpRequest;Lcom/vmware/vapi/internal/protocol/client/rpc/HttpRequest$HttpResponseHandler;)V\n\tat com.vmware.vapi.vmc.client.authz.CspAccessRequestor.requestAccess(CspAccessRequestor.java:52)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor.refreshContext(AuthzRefreshingRequestExecutorFactory.java:215)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor.refreshContextIfNeeded(AuthzRefreshingRequestExecutorFactory.java:171)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor.execute(AuthzRefreshingRequestExecutorFactory.java:105)\n\tat com.vmware.vapi.internal.protocol.client.rest.RestClientApiProvider.invoke(RestClientApiProvider.java:71)\n\tat com.vmware.vapi.internal.bindings.Stub.invoke(Stub.java:227)\n\tat com.vmware.vapi.internal.bindings.Stub.invoke(Stub.java:208)\n\tat com.vmware.vapi.internal.bindings.Stub.invokeMethodAsync(Stub.java:172)\n\tat com.vmware.vapi.internal.bindings.Stub.invokeMethod(Stub.java:140)\n\tat com.vmware.vmc.OrgsStub.list(OrgsStub.java:82)\n\tat com.vmware.vmc.OrgsStub.list(OrgsStub.java:75)

## Environment
- SDK version: vapi-runtime-2.10.1.jar

- Java version:

1.8.0
- vSphere version:
6.8
## Steps or code snippet to reproduce
I see this issue after moving to vapi-runtime-1.10.1.jar. My code works with vapi-runtime-1.9.0.jar

**Comment by vinpai** [comment]
Can you paste your complete code sample here ? These are VMC console APIs to be specifically run against the public cloud https://vmc.vmware.com.

**Comment by datvmc** [comment]
I tried with the new vmc-sdk-common-1.3.0 jar. The OrgsStub.list() call goes through now.

However, the following code to get the list of NSX-T domains runs into an exception:

nsxApiClient = VmcNsxClients.custom()
                .setBaseUrl(vmcUrl)
                .setAuthorizationUrl(cspUrl)
                .setRefreshToken(refreshToken)
                .setOrganizationId(orgId)
                .setSddcId(sddcId)
                .build();
Domains domains = nsxApiClient.createStub(Domains.class);
DomainListResult domainsList = domains.list(null, null, 1000L, false, null);

Exception:
Error deserializing message.com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')\n at [Source: java.io.ByteArrayInputStream@771522ac; line: 1, column: 2]\n\tat com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)\n\tat com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)\n\tat com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462)\n\tat com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2613)\n\tat com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:841)\n\tat com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:737)\n\tat com.vmware.vapi.internal.protocol.common.json.JsonDirectDeserializer.deserialize(JsonDirectDeserializer.java:34)\n\tat com.vmware.vapi.internal.protocol.client.rest.DefaultBodyConverter.getResult(DefaultBodyConverter.java:41)\n\tat com.vmware.vapi.internal.protocol.client.rest.StatusCodeErrorConverter.parseResponseBody(StatusCodeErrorConverter.java:128)\n\tat com.vmware.vapi.internal.protocol.client.rest.StatusCodeErrorConverter.buildErrorValue(StatusCodeErrorConverter.java:109)\n\tat com.vmware.vapi.internal.protocol.client.rest.StatusCodeErrorConverter.getError(StatusCodeErrorConverter.java:103)\n\tat com.vmware.vapi.internal.protocol.client.rest.DefaultResponseParser.parseError(DefaultResponseParser.java:38)\n\tat com.vmware.vapi.internal.protocol.client.rest.BaseResponseParser.parse(BaseResponseParser.java:29)\n\tat com.vmware.vapi.internal.protocol.client.rest.DefaultRequestExecutorFactory$DefaultHttpResponseHandler.onResult(DefaultRequestExecutorFactory.java:86)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor$AuthzRefreshingHttpResponseHandler.onResult(AuthzRefreshingRequestExecutorFactory.java:160)\n\tat com.vmware.vapi.internal.protocol.client.rpc.http.ApacheClientRestTransport.execute(ApacheClientRestTransport.java:79)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor.authorizeAndExecute(AuthzRefreshingRequestExecutorFactory.java:112)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor.access$100(AuthzRefreshingRequestExecutorFactory.java:58)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor$1.onComplete(AuthzRefreshingRequestExecutorFactory.java:98)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor.refreshContext(AuthzRefreshingRequestExecutorFactory.java:188)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor.refreshContextIfNeeded(AuthzRefreshingRequestExecutorFactory.java:171)\n\tat com.vmware.vapi.vmc.client.authz.AuthzRefreshingRequestExecutorFactory$AuthzRefreshingRequestExecutor.execute(AuthzRefreshingRequestExecutorFactory.java:105)\n\tat com.vmware.vapi.internal.protocol.client.rest.RestClientApiProvider.invoke(RestClientApiProvider.java:71)\n\tat com.vmware.vapi.internal.bindings.Stub.invoke(Stub.java:227)\n\tat com.vmware.vapi.internal.bindings.Stub.invoke(Stub.java:208)\n\tat com.vmware.vapi.internal.bindings.Stub.invokeMethodAsync(Stub.java:172)\n\tat com.vmware.vapi.internal.bindings.Stub.invokeMethod(Stub.java:140)\n\tat com.vmware.nsx_policy.infra.DomainsStub.list(DomainsStub.java:123)\n\tat com.vmware.nsx_policy.infra.DomainsStub.list(DomainsStub.java:111)\n\tat 

This is with vapi-runtime-2.10.1 and the new vmc-sdk-common-1.3.0. It doesn't happen with vapi-runtime-2.9.0 and the previous vmc-sdk-common-1.3.0

**Comment by ggoodvmw** [comment]
Hi datvmc - I don't see anything obviously wrong with your code, but it does look like you're getting back a non-JSON response. Maybe try catching the exception and examining it in the debugger?

Here is a sample I wrote that is working for me - it's successfully listing the Domain objects in my SDDC.

https://github.com/vmwaresamples/nsx-t/blob/master/java/src/main/java/com/vmware/nsx/examples/basics/Vmc.java

**Comment by datvmc** [comment]
Thanks ggoodvmw for taking a look. I added a exception block but unfortunately not able to reproduce this anymore. The call goes through successfully now without throwing an exception.
Please feel free to close this as resolved.
