### ISSUE TITLE
element  linkXRef is not allowed  intelij

### ISSUE THREAD

**Issue by zhaoya881010** [vmware/vsphere-automation-sdk-java#44]
i used intelij import sdk,found pom.xml "element  linkXRef is not allowed".

**Comment by kunal-pmj** [comment]
This seem to an issue with the intellij and Maven plugin compatibility.
[Intellij not reconize configuration maven-checkstyle-plugin](https://stackoverflow.com/questions/51452501/intellij-not-reconize-configuration-maven-checkstyle-plugin)
Though this is not related to the automation sdk java. We will see if there is a way to avoid this error.  

thanks
Kunal

**Comment by zhaoya881010** [comment]
@kunal-pmj i try delete linkXRef ,it's ok.  i not sure is no problem it to do.

**Comment by kunal-pmj** [comment]
Thanks

I am closing the issue

regards
Kunal

**Comment by Divyachd** [comment]
I am still facing this issue. Changing Maven version in IntelliJ doesn't help

**Comment by Shubham-arora-tricon** [comment]
@kunal-pmj how can we avoid this error?
Could you please help me?

**Comment by kunal-pmj** [comment]
Hi @Shubham-arora-tricon 

this is an Intellij issue.
