### ISSUE TITLE
create cluster api？

### ISSUE THREAD

**Issue by zhaoya881010** [vmware/vsphere-automation-sdk-java#45]
the ClusterStub class no create cluster method？i not found......

**Comment by kunal-pmj** [comment]
Hi @zhaoya881010 

The API create/update cluster apis are not available in the ClusterStub. Since, this REST apis sdk is pretty new. APIS are being added gradually. 

While these APIs are added and made available via SDK. You can use the  use the SOAP apis for missing REST APIS. 

thanks
Kunal

**Comment by jobingeo** [comment]
Closing this now as this feature is not yet available in vsphere-automation-sdk
