### ISSUE TITLE
There are no descriptions of the Libraries bundled with the SDK

### ISSUE THREAD

**Issue by kunal-pmj** [vmware/vsphere-automation-sdk-java#49]
- [ ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [ ] This API is compatible with my vCenter version (You can get this info from the API documentation )
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Description
The Description of Libraries are missing from the [library documentation](https://github.com/vmware/vsphere-automation-sdk-java/tree/master/lib)
## Environment
- SDK version: 

- Java version:

- vSphere version:

**Comment by kunalpmj** [comment]
Starting release 9.0. The libraries will be picked from maven central.
Closing the issue
