### ISSUE TITLE
Provide an independent truststore and keystore for TLS connections made by the SDK

### ISSUE THREAD

**Issue by schnekli** [vmware/vsphere-automation-sdk-java#53]
- [ X] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [ X] This API is compatible with my vCenter version (You can get this info from the API documentation )
- [ X] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Description
When I use the SDK as part of a larger application, I want the Truststore and Keystore that the SDK uses to connect to the lookup service & to VC be different than for other entities in the JVM making TLS connections. It would be nice to be able to provide an SSLSocketFactory that the SDK can use for its own TLS connections. That way the SDK doesn't interfere with the rest of the application. If it's already possible to do this, please let me know how.

## Environment
- SDK version: vsphere-samples-6.7.1.jar

- Java version: 1.8.0_144

- vSphere version: N/A

**Comment by kunal-pmj** [comment]
An independent Truststore can be setup for the SDK. The TLS validation in place is only for the demonstration purpose. the SSL verification if disabled for a sample, remains disabled for the entire JVM. If you want to change that behaviour then provide a TrustStore path to the samples
