### ISSUE TITLE
why CustomizationIPSettings not setNicSettingMap method？

### ISSUE THREAD

**Issue by zhaoya881010** [vmware/vsphere-automation-sdk-java#54]
vsphere web service sdk 6.7 

public static CustomizationSpec createCustomizations(){
        CustomizationSpec spec=new CustomizationSpec();
......      
......
        adapter.setAdapter(ipSetting);
        adapterMappings[0]=adapter;
        spec.setNicSettingMap(adapterMappings);        
        CustomizationSpecItem customizationSpecItem=new CustomizationSpecItem();
        customizationSpecItem.setSpec(spec);
        CustomizationSpecInfo info=new CustomizationSpecInfo();
        info.setName("123456");
       info.setDescription("123456");
        customizationSpecItem.setInfo(info);       
        return spec;
    }

error:

The method setNicSettingMap(CustomizationAdapterMapping[]) is undefined for the type CustomizationSpec

**Comment by kunal-pmj** [comment]
Hi @zhaoya881010 

for queries with vsphere web service sdk, contact VMWare GSS.

Thanks
Kunal
