### ISSUE TITLE
--Skip-server-verification  not working

### ISSUE THREAD

**Issue by Pyntamilselvi** [vmware/vsphere-automation-sdk-java#78]
- [ ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [ ] This API is compatible with my vCenter version (You can get this info from the API documentation )
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Description
Encountering an error during uploading files to CL with the help of OvfImportExport.Java sample class from vsphere (6.7).
An error is thrown and please find below for the error description. While debugging the error ,found ignored flag being set to false which should be ideally be true. Hence tried the below approach.
Tried updating the upload session with the respective PATCH API as per API reference doc but failed. The API is response is 200 but the parameter is nor getting updated to true.
For reference session info:
{"update_spec":{"library_item_id":"55a31c5a-9ac5-4304-b55d-6acc38ee4bb9","client_progress":0,"expiration_time":"2019-08-23T06:15:07.217Z","preview_info":{"warnings":[{"ignored":true,"type":"SELF_SIGNED_CERTIFICATE","message":{"args":[],"default_message":"The certificate is self-signed.","id":"com.vmware.vdcs.vsphere-cs-lib.CERTIFICATE_SELF_SIGNED"}},{"ignored":true,"type":"UNTRUSTED_CERTIFICATE","message":{"args":[],"default_message":"The certificate is not trusted.","id":"com.vmware.vdcs.vsphere-cs-lib.CERTIFICATE_UNTRUSTED"}}],"state":"AVAILABLE","certificate_info":{"x509":"String","subject":"EMAILADDRESS=test, CN=test, OU=test, O=test, L=test, ST=test, C=US","self_signed":true,"issuer":"EMAILADDRESS=test, CN=test, OU=test, O=test, L=test, ST=test, C=US"}},"id":"04e50d4c-fb24-4136-9822-61542c625a6a:c7f7ee5d-af0d-4c7e-a387-9561d1fb2bf9","library_item_content_version":"1","state":"ACTIVE"}}
## Environment: Development environment.
- SDK version: 6.7
- Java version:
java version "1.8.0_221"
Java (TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) Client VM (build 25.221-b11, mixed mode, sharing)
- vSphere version:

## Actual behaviour:
Trying to deploy OVF file to the content library via OvfImportExport.Java. It is in the development environment, hence bypassing the client-side validation with the –skip-server-verification parameter. But uploading files to CL is failing with the below mentioned warning,
Catchedcom.vmware.vapi.std.errors.NotAllowedInCurrentState: NotAllowedInCurrentState (com.vmware.vapi.std.errors.not_allowed_in_current_state) => {
   messages = [LocalizableMessage (com.vmware.vapi.std.localizable_message) => {
   id = com.vmware.vdcs.cls-main.update_session_invalid_state_for_operation_reason,
   defaultMessage = The operation fail can not be invoked when the import session is in the ERROR state. Reason: The certificate is self-signed. The certificate is not trusted.,
   args = [fail, ERROR, The certificate is self-signed. The certificate is not trusted.],
   params = <null>,
   localized = <null>
}],
   data = <null>,
   errorType = NOT_ALLOWED_IN_CURRENT_STATE
}
## Expected behaviour
Uploading files to CL with self-singed certificate.

**Comment by Pyntamilselvi** [comment]
"warnings": [{
			"type": {
				"name": "SELF_SIGNED_CERTIFICATE"
			},
			"message": {
				"id": "com.vmware.vdcs.vsphere-cs-lib.CERTIFICATE_SELF_SIGNED",
				"defaultMessage": "The certificate is self-signed.",
				"args": []
			},
			"ignored": false
		}, {
			"type": {
				"name": "UNTRUSTED_CERTIFICATE"
			},
			"message": {
				"id": "com.vmware.vdcs.vsphere-cs-lib.CERTIFICATE_UNTRUSTED",
				"defaultMessage": "The certificate is not trusted.",
				"args": []
			},
			"ignored": false
		}]

How to make the ignored property to true?

**Comment by dingziyang** [comment]
Me too. Can you tell me , How to set 'Skip verification of server certificate' in rest api used? Please.

**Comment by sumitAgrawal007** [comment]
I am looking at this, will get back to you.

**Comment by dingziyang** [comment]
I'm in a hurry. I'll wait online. @sumitAgrawal007

**Comment by sumitAgrawal007** [comment]
Looks like this issue was fixed.
Are you using the latest master branch ?
https://github.com/vmware/vsphere-automation-sdk-java/blob/02ce5dd589ab74574fca0a7c206bf093bd0f5e8d/src/main/java/vmware/samples/common/authentication/VapiAuthenticationHelper.java#L235

**Comment by dingziyang** [comment]
I just used rest api by HttpClient, not use java sdk. Like that:

`static {
        try {
            
            SSLContext sslContext = new SSLContextBuilder().loadTrustMaterial(null, new TrustStrategy() {
                
                public boolean isTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                    return true;
                }
            }).build();
            SSLConnectionSocketFactory sslsf = new SSLConnectionSocketFactory(sslContext);
            Registry<ConnectionSocketFactory> socketFactoryRegistry = RegistryBuilder.<ConnectionSocketFactory>create()
                    .register("http", PlainConnectionSocketFactory.getSocketFactory())
                    .register("https", sslsf)
                    .build();

            pccm = new PoolingHttpClientConnectionManager(socketFactoryRegistry);
            pccm.setDefaultMaxPerRoute(30); 
            pccm.setMaxTotal(200);
        } catch (KeyManagementException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (KeyStoreException e) {
            e.printStackTrace();
        }
    }

    private static HttpClient getHttpClient() {

        int REQUEST_TIMEOUT = 20 * 1000;  
        int SO_TIMEOUT = 20 * 1000;       
        RequestConfig defaultRequestConfig = RequestConfig.custom()
                .setSocketTimeout(SO_TIMEOUT)
                .setConnectTimeout(REQUEST_TIMEOUT)
                .setConnectionRequestTimeout(REQUEST_TIMEOUT)
                .setStaleConnectionCheckEnabled(true)
                .build();

        CloseableHttpClient httpClient = HttpClients.custom().setConnectionManager(pccm).setDefaultRequestConfig(defaultRequestConfig).build();
        return httpClient;
    }`

**Comment by sumitAgrawal007** [comment]
Can you include the sslconfig method while building the sslcontext
  private SslConfiguration buildSslConfiguration(boolean skipServerVerification) throws Exception {
	  SslConfiguration sslConfig;
	  //if(skipServerVerification) {
          SslUtil.trustAllHttpsCertificates();
          sslConfig = new SslConfiguration.Builder()
      		.disableCertificateValidation()
      		.disableHostnameVerification()
      		.getConfig();
	 

      return sslConfig;
  }
}

**Comment by dingziyang** [comment]
No class: SslConfiguration

**Comment by dingziyang** [comment]
I wonder if there is a parameter in the request, such as in the header, which is equivalent to 'boolean skipServerVerification'.

**Comment by sumitAgrawal007** [comment]
No, there is no such param.
Actually, in the client when you build the httpconfig, you have to include the custom SSLConfig making it trustAllCertificates.
public HttpConfiguration buildHttpConfiguration(boolean skipServerVerification) throws Exception {
      ```
HttpConfiguration httpConfig =
          new HttpConfiguration.Builder()
          .setSslConfiguration(buildSslConfiguration(skipServerVerification))
          .getConfig();        
      return httpConfig;
  }
private SslConfiguration buildSslConfiguration(boolean skipServerVerification) throws Exception {
	  SslConfiguration sslConfig;
	  //if(skipServerVerification) {
          SslUtil.trustAllHttpsCertificates();
          sslConfig = new SslConfiguration.Builder()
      		.disableCertificateValidation()
      		.disableHostnameVerification()
      		.getConfig();
	 

      return sslConfig;
  }
}

```

**Comment by sumitAgrawal007** [comment]
You can do something like this
https://stackoverflow.com/questions/2642777/trusting-all-certificates-using-httpclient-over-https

**Comment by dingziyang** [comment]
Thank you very much. It is worked by stackoverflow code.
