### ISSUE TITLE
Unable to build docker container

### ISSUE THREAD

**Issue by gavinbarnard** [vmware/vsphere-automation-sdk-java#98]
- [X] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [X] This API is compatible with my vCenter version (You can get the info from the Java API Reference Documentation)
- [X] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- sdk binding version: 
lib/vsphereautomation-client-sdk-3.2.0.jar

- Java version:
root@3f7ed95c64d7:/work/vsphere-automation-sdk-java# java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode)

- vSphere version: VMConAWS 1.8 & 1.9

- Operating System/Shell (used to run SDK-based apps): MacOS (10.13.6 (17G9016)) and Ubuntu 18.04 

## Steps or code snippet to reproduce: 
docker build https://github.com/vmware/vsphere-automation-sdk-java.git#:docker -t vmware/vsphere-automation-sdk-java

## Actual behavior

[INFO] Changes detected - recompiling the module!
[INFO] Compiling 109 source files to /work/vsphere-automation-sdk-java/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /work/vsphere-automation-sdk-java/src/main/java/vmware/samples/common/authentication/VimAuthenticationHelper.java:[17,19] error: package javax.xml.ws does not exist
[ERROR] /work/vsphere-automation-sdk-java/src/main/java/vmware/samples/sso/soaphandlers/HeaderHandlerResolver.java:[19,27] error: package javax.xml.ws.handler does not exist
[ERROR] /work/vsphere-automation-sdk-java/src/main/java/vmware/samples/sso/soaphandlers/HeaderHandlerResolver.java:[20,27] error: package javax.xml.ws.handler does not exist
[ERROR] /work/vsphere-automation-sdk-java/src/main/java/vmware/samples/sso/soaphandlers/HeaderHandlerResolver.java:[21,27] error: package javax.xml.ws.handler does not exist
[ERROR] /work/vsphere-automation-sdk-java/src/main/java/vmware/samples/sso/soaphandlers/HeaderHandlerResolver.java:[29,52] error: cannot find symbol

## Expected behavior
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ vsphere-samples-nodeps ---
[INFO] Installing /work/vsphere-automation-sdk-java/target/vsphere-samples-7.0.0.jar to /root/.m2/repository/com/vmware/vsphere-samples-nodeps/7.0.0/vsphere-samples-nodeps-7.0.0.jar
[INFO] Installing /work/vsphere-automation-sdk-java/pom.xml to /root/.m2/repository/com/vmware/vsphere-samples-nodeps/7.0.0/vsphere-samples-nodeps-7.0.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  41.823 s
[INFO] Finished at: 2020-01-27T20:24:32Z
[INFO] ------------------------------------------------------------------------

Fixed by adding com.sun.xml.ws, javax.xml.ws, and com.sun.org.apache.xml.internal dependencies to pom.xml  see my fork: https://github.com/gavinbarnard/vsphere-automation-sdk-java
```
gavin@docker-dox:~/vsphere-automation-sdk-java$ git diff 5f6d2a9a0267460a93bc7fcf243a745b4c347ede pom.xml
diff --git a/pom.xml b/pom.xml
index 1c06cc74e..6a6c65bf4 100644
--- a/pom.xml
+++ b/pom.xml
@@ -416,6 +416,21 @@
   <artifactId>commons-beanutils</artifactId>
   <version>${commons-beanutils.version}</version>
  </dependency>
+ <dependency>
+  <groupId>com.sun.xml.ws</groupId>
+  <artifactId>rt</artifactId>
+  <version>2.3.1</version>
+ </dependency>
+ <dependency>
+  <groupId>javax.xml.ws</groupId>
+  <artifactId>jaxws-api</artifactId>
+  <version>2.3.1</version>
+ </dependency>
+ <dependency>
+  <groupId>com.sun.org.apache.xml.internal</groupId>
+  <artifactId>resolver</artifactId>
+  <version>20050927</version>
+ </dependency>
 </dependencies>
  <reporting>
   <plugins>
```

**Comment by gavinbarnard** [comment]
`gavin@docker-dox:~/vsphere-automation-sdk-java$ git diff 5f6d2a9a0267460a93bc7fcf243a745b4c347ede pom.xml
diff --git a/pom.xml b/pom.xml
index 1c06cc74e..6a6c65bf4 100644
--- a/pom.xml
+++ b/pom.xml
@@ -416,6 +416,21 @@
   <artifactId>commons-beanutils</artifactId>
   <version>${commons-beanutils.version}</version>
  </dependency>
+ <dependency>
+  <groupId>com.sun.xml.ws</groupId>
+  <artifactId>rt</artifactId>
+  <version>2.3.1</version>
+ </dependency>
+ <dependency>
+  <groupId>javax.xml.ws</groupId>
+  <artifactId>jaxws-api</artifactId>
+  <version>2.3.1</version>
+ </dependency>
+ <dependency>
+  <groupId>com.sun.org.apache.xml.internal</groupId>
+  <artifactId>resolver</artifactId>
+  <version>20050927</version>
+ </dependency>
 </dependencies>
  <reporting>
   <plugins>`

**Comment by gavinbarnard** [comment]
```
gavin@docker-dox:~/vsphere-automation-sdk-java$ git diff 5f6d2a9a0267460a93bc7fcf243a745b4c347ede pom.xml
diff --git a/pom.xml b/pom.xml
index 1c06cc74e..6a6c65bf4 100644
--- a/pom.xml
+++ b/pom.xml
@@ -416,6 +416,21 @@
   <artifactId>commons-beanutils</artifactId>
   <version>${commons-beanutils.version}</version>
  </dependency>
+ <dependency>
+  <groupId>com.sun.xml.ws</groupId>
+  <artifactId>rt</artifactId>
+  <version>2.3.1</version>
+ </dependency>
+ <dependency>
+  <groupId>javax.xml.ws</groupId>
+  <artifactId>jaxws-api</artifactId>
+  <version>2.3.1</version>
+ </dependency>
+ <dependency>
+  <groupId>com.sun.org.apache.xml.internal</groupId>
+  <artifactId>resolver</artifactId>
+  <version>20050927</version>
+ </dependency>
 </dependencies>
  <reporting>
   <plugins>
```

**Comment by kunal-pmj** [comment]
Hi Gavin

The SDK and samples are developed using Java 8. Since JDK 1.8 provides the JEE libraries under JRE lib. There is no need to add them as dependency. 
Since you are using openjdk 11.0.6 2020-01-14. It is required to add the dependencies for Java EE libraries. 
Java EE libraries were marked  deprecated in Java 9 and finally removed in Java 11.  

thanks
Kunal

**Comment by gavinbarnard** [comment]
For the docker container build is there any way to specify which version of Java is picked up then?

In both my MacOS and Ubuntu runs the JDK 11.x was chosen automatically?

**Comment by gavinbarnard** [comment]
FROM maven:3.6.3-jdk-8-openj9 in Dockerfile

instead of maven:latest fixes the issue without changes being needed to pom.xml

**Comment by shylasrinivas** [comment]
Hi Gavin, wanted to check in regarding this issue. Are you still waiting on any information? If the issue is resolved, can you please close it?

Thanks!

**Comment by gavinbarnard** [comment]
I am unblocked, but the main vmware/vsphere-automation-sdk-java is still broken with bad information in the Dockerfile.    As long as it remains pulling maven:latest people will get jdk 11 and the build will fail.

**Comment by shylasrinivas** [comment]
Thanks Gavin. We'll work on the fix and notify when its ready.

**Comment by shylasrinivas** [comment]
I have merged the changes for maven jdk version. Can you verify if docker build works for you with the latest changes?

**Comment by gavinbarnard** [comment]
looks good now, thank you

gavinbarnar-a01:test gavinbarnard$ docker build https://github.com/vmware/vsphere-automation-sdk-java.git#:docker -t vmware/vsphere-automation-sdk-java

`[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ vsphere-samples-nodeps ---
[INFO] Installing /work/vsphere-automation-sdk-java/target/vsphere-samples-7.0.0.jar to /root/.m2/repository/com/vmware/vsphere-samples-nodeps/7.0.0/vsphere-samples-nodeps-7.0.0.jar
[INFO] Installing /work/vsphere-automation-sdk-java/pom.xml to /root/.m2/repository/com/vmware/vsphere-samples-nodeps/7.0.0/vsphere-samples-nodeps-7.0.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:43 min
[INFO] Finished at: 2020-02-11T19:51:40Z
[INFO] ------------------------------------------------------------------------
Removing intermediate container bf3a0d8fae23
 ---> d6a3b7cd5629
Step 9/9 : CMD ["/bin/bash"]
 ---> Running in 49dad2362b44
Removing intermediate container 49dad2362b44
 ---> e5e97a009f8a
Successfully built e5e97a009f8a
Successfully tagged vmware/vsphere-automation-sdk-java:latest`
